// ============================================================
// INITIATIVE DATA — Updated August 2026 (strategy flags filled in)
//
// MONTHLY UPDATE INSTRUCTIONS:
// 1. Upload the new Shared_services spreadsheet to Claude
// 2. Ask Claude to regenerate this file
// 3. Replace this file in src/data.js
// 4. Commit -> Vercel auto-deploys
// ============================================================

export const DATA_META = {
  updatedDate: "August 2026",
  totalActive: 62,
  changeLog: [
    { type: "data", text: "Strategy Aligned flag filled in for 17 items: 5 Yes (Custody Licensed Software PoC, Terraform Providers Upgrade, AvaCloud indexer infra, SETTL enablement, AvaCloud ip-restriction), 12 No" },
    { type: "data", text: "Strategy now 25 Yes / 29 No / 8 blank. Blank items keep the default 10 pts until filled in" },
    { type: "data", text: "No other changes: same 62 active items, statuses, and priorities as the previous August run" },
  ],
};

export const INITIATIVES = [
  {
    "MotherEPIC": "Avacloud - new functionality",
    "Roadmap item": "Interoperability L1-to-L1 flows",
    "Business Value/Purpose": "Add workflow so users can request L1-to-L1 support for AWM relayers. AWM deploy through storm and deploy in any region",
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": "AC-25O4KR1",
    "Status": "OnHold",
    "Priority ": 3.0,
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "STORM",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Technical improvement",
    "Roadmap item": "Provision Let's encrypt certificates for enclave market",
    "Business Value/Purpose": "Strengthen security to ecrypt certificates for enclave market",
    "2026 AVL Strategy Aligned": "No",
    "OKR": "INFRA-25O4KR2",
    "Status": "Blocked",
    "Priority ": 1.0,
    "LoB": "Foundation",
    "Estimated Effort (FTE Weeks)": 3.0,
    "Classification": "Request",
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Cost Optimisation",
    "Roadmap item": "Avacloud EU-central cluster decomissioning",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": 0.0,
    "LoB": "Infra: Cost Optimization",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Maintenance",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Cost Optimization",
    "Roadmap item": "Setup Grafana/Prometheus for monitoring",
    "Business Value/Purpose": "Setup Grafana/Prometheus as solution replacing DataDog observability to reduce the maintenance costs",
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": 0.0,
    "LoB": "Infra: Cost Optimization",
    "Estimated Effort (FTE Weeks)": 20.0,
    "Classification": "Request",
    "Main Team": "SRE",
    "Dependency": "Enterprise Support",
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Maintenance",
    "Roadmap item": "Kubernetes 1.33 upgrade",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": 0.0,
    "LoB": "Infra: Cost Optimization",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Maintenance",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": 4.0,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Avacloud - new functionality",
    "Roadmap item": "Implement Testnet in Europe (Glacier excluded) - OCI preferred",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "OnHold",
    "Priority ": 3.0,
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": 4.0,
    "Classification": "Request",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Security Compliance",
    "Roadmap item": "AvaCloud ISO2700.. to achieve",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": "INFRA-25O2KR2",
    "Status": "OnHold",
    "Priority ": 1.0,
    "LoB": "Security",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Avacloud - new functionality",
    "Roadmap item": "LATAM Regional support for AvaCloud",
    "Business Value/Purpose": "subnets-testnet, subnets-mainnet",
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "OnHold",
    "Priority ": 1.0,
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": 3.0,
    "Classification": "Request",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Security Engineering",
    "Roadmap item": "Followup item on github actions, CI, credentials rotation, etc.",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "OnHold",
    "Priority ": 2.0,
    "LoB": "Security",
    "Estimated Effort (FTE Weeks)": 2.0,
    "Classification": "Consultation",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Avacloud - new functionality",
    "Roadmap item": "On Chain Privacy Support - DHE (Stablecoin offering powered by Avacy?)",
    "Business Value/Purpose": "DHE - Will to write tech on this. May required particular resoure for pogramatic privacy for chain. preserving smart contracts.",
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": "AC-25O2KR1",
    "Status": "OnHold",
    "Priority ": 20.0,
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Custody - new functionality",
    "Roadmap item": "Node.js infrastrcuture for API",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": 1.0,
    "LoB": "Custody",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Technical improvementt - cost reduction",
    "Roadmap item": "Grafana project ramp up",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": 1.0,
    "LoB": "Infra: Cost Optimization",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Maintenance",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": 4.0,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Custody - new functionality",
    "Roadmap item": "Custody External client solution onboarding (Custody Production Operationalization)",
    "Business Value/Purpose": "Provide custody with the cost effcient solution to onboard new external customers for custodianship",
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": "INFRA-25O4KR2",
    "Status": "OnHold",
    "Priority ": 1.0,
    "LoB": "Custody",
    "Estimated Effort (FTE Weeks)": 4.0,
    "Classification": "Request",
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Maintenance",
    "Roadmap item": "Q1 2026 Custody Operational Support (Misc. requests)",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": 0.0,
    "LoB": "Custody",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": 5.0,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Deploying eL1s (encrypted L1s)",
    "Business Value/Purpose": "Requries like custom pre-compile, etc. Looks like a duplicate with Avacy precompiles. In AvaCloud development for Q4 2025. On hold",
    "2026 AVL Strategy Aligned": null,
    "OKR": null,
    "Status": "OnHold",
    "Priority ": 2.0,
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": 2.0,
    "Classification": "Request",
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": 0.0,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "API Gateway",
    "Roadmap item": "AvaCloud APi Gateway = ANATOLIY remembers! [Optional but important]",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "New",
    "Priority ": 2.0,
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": 4.0,
    "Q2 2026 plan": 0.0,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Maintenance",
    "Roadmap item": "Q1 2026 Operational Support/On-call",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": 0.0,
    "LoB": "Infra: Maintenance",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Incident",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": 15.0,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Generalized Region support for AvaCloud",
    "Roadmap item": "Gas Relayer rewrite to GoLang - infra support",
    "Business Value/Purpose": "Aimed at better scaling, supportability (Go Lang), and cost reduction.",
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": "AC-25O1KR1",
    "Status": "In Progress",
    "Priority ": 6.0,
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": 0.0,
    "Q2 2026 plan": null,
    "Q3 2026 plan": 4.0
  },
  {
    "MotherEPIC": "Technical improvementt - cost reduction",
    "Roadmap item": "SRE Operational Excellence (Q3 2025 - Q3 2026)",
    "Business Value/Purpose": "Improves operational effciency of the infrastructure and helps to identify cost saving and service quality improvement opprotunities",
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": "High",
    "LoB": "PEG",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": "Maintenance",
    "Roadmap item": "Perform DR tests (tabletop + test envinroments)",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "To Do",
    "Priority ": 1.0,
    "LoB": "Security",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Maintenance",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": 0.0,
    "Q2 2026 plan": 2.0,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Reliability",
    "Roadmap item": "Terraform Providers Upgrade and Global Provider Decoupling",
    "Business Value/Purpose": "Improved service reliability and security by keeping Terraform providers up2date",
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": "Highest",
    "LoB": "PEG",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": "Maintenance",
    "Roadmap item": "Custody Security Improvements (logs provisioning to SIEM [Security], ACR)",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "New",
    "Priority ": 1.0,
    "LoB": "Custody",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": 2.0,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Security Compliance",
    "Roadmap item": "ECR permissions and tag mutability allow for supply chain attacks",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": 1.0,
    "LoB": "Security",
    "Estimated Effort (FTE Weeks)": 1.0,
    "Classification": "Request",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Security Compliance",
    "Roadmap item": "Custody prep for SOC2 (Q2 - June)",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": 1.0,
    "LoB": "Security",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Maintenance",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": 2.0,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Reliability",
    "Roadmap item": "Redundancy and scaling improvements",
    "Business Value/Purpose": "For Core, improves reliability and availability of the Core wallet",
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "Selected for Development",
    "Priority ": "Medium",
    "LoB": "Core",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": "Core - technical improvements",
    "Roadmap item": "Upgrade Core staging infra to more powerful nodes",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "New",
    "Priority ": 2.0,
    "LoB": "Core",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": 1.0,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Technical improvementt - cost reduction",
    "Roadmap item": "Enable decomissioning of the namespace if full L1 decomissioned",
    "Business Value/Purpose": "Currently when L1 is decomissioned from the cloud it leaves empty namespace behind.",
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "New",
    "Priority ": 3.0,
    "LoB": "Infra: Technical Improvement",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Maintenance",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": 0.0,
    "Q2 2026 plan": 2.0,
    "Q3 2026 plan": "X"
  },
  {
    "MotherEPIC": "Maintenance",
    "Roadmap item": "Update OKE and cycle nodes",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": 2.0,
    "LoB": "Security",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Maintenance",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": 2.0,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Security Compliance",
    "Roadmap item": "Disaster Recovery Testing",
    "Business Value/Purpose": "Improves availability and resilience fo the systems - specifically imrptant for enteprise customers",
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "To Do",
    "Priority ": 1.0,
    "LoB": "Infra: Technical Improvement",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Maintenance",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": 0.0,
    "Q2 2026 plan": 2.0,
    "Q3 2026 plan": "X"
  },
  {
    "MotherEPIC": "Security Engineering",
    "Roadmap item": "OIDC for github actions [infra assistance + testing]",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "New",
    "Priority ": 3.0,
    "LoB": "Security",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": 2.0,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Technical improvement - quality",
    "Roadmap item": "E2E test for operators",
    "Business Value/Purpose": "It's a technical improvement on our existing E2E tests, to:\n\t\tAdd a devnet or local network to AvagoOperator to create healthy validators during tests, this will improve the efficiency and quality of our tests\n\t\tConfigure Cannon operator to be able to create secrets using respective cloud providers AWS, GCP, OCI. This would improve the quality of our tests by adding this ability and also asserts for expected or predicatable behaviour of the operator.\n\nScope:\n\t\tAvago Operator: requires some Avalanche network knowledge and possible consultation with platform team\n\t\tCannon operator: Would need help from either security or solution architect team on providing access for the tests to create secrets\n\nImplementing should take max of 3 weeks subject to all the requirements being available.",
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "New",
    "Priority ": 1.0,
    "LoB": "Infra: Technical Improvement",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Maintenance",
    "Main Team": "STORM",
    "Dependency": null,
    "Q1 2026 plan": 4.0,
    "Q2 2026 plan": 0.0,
    "Q3 2026 plan": "X"
  },
  {
    "MotherEPIC": "Technical improvementt - cost reduction",
    "Roadmap item": "OCI migration for Platform (non-validator)",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "New",
    "Priority ": 2.0,
    "LoB": "PEG",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Maintenance",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": "Technical improvement - quality",
    "Roadmap item": "Improve observability of Storm",
    "Business Value/Purpose": "Improve infrastrcuture services by improving Storm API monitoring",
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": 2.0,
    "LoB": "Infra: Technical Improvement",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Maintenance",
    "Main Team": "STORM",
    "Dependency": null,
    "Q1 2026 plan": 2.0,
    "Q2 2026 plan": 2.0,
    "Q3 2026 plan": "X"
  },
  {
    "MotherEPIC": "Core - technical improvements",
    "Roadmap item": "Replace DockerHub with alternative (AWS ECR)",
    "Business Value/Purpose": "DockerHub provides limited access and funcitonality. Need an ability to physically create repos.",
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "OnHold",
    "Priority ": 99.0,
    "LoB": "Core",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": 1.0,
    "Q2 2026 plan": null,
    "Q3 2026 plan": null
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "DevNet for AvaCloud to support Platform upgrades (H-upgrade)",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": null,
    "OKR": null,
    "Status": "Blocked",
    "Priority ": "High",
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Achilles Improvements",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": null,
    "OKR": null,
    "Status": "Backlog",
    "Priority ": "Medium",
    "LoB": "PEG",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Storm AppSet migration",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "Review / Testing",
    "Priority ": "Medium",
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "STORM",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "STORM will need to operate in 3 isolated repositories for managing L1s",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": "Medium",
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "STORM",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Platform infrastructure simplification",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": "High",
    "LoB": "PEG",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "FinOps Management Q3-2026",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": "Medium",
    "LoB": "Infra: Cost Optimization",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "FinOps",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "AvaCloud Grafana dashboard deployment improvement",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": null,
    "OKR": null,
    "Status": "Blocked",
    "Priority ": "Medium",
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Managed node resource config in a structured way",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": null,
    "OKR": null,
    "Status": "Backlog",
    "Priority ": "Low",
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "STORM",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "AvaCloud indexer deployment infrastructure management",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "Selected for Development",
    "Priority ": "High",
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "STORM",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "AvaCloud ip-restriction [whitelisting] for L1s automation",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "Selected for Development",
    "Priority ": "Low",
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "STORM",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Storm Technical Debt [Q3 2026]",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": "High",
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "STORM",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "SETTL infrastructure enablement [Q3 2026]",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": "High",
    "LoB": "SETTL",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Q3 2026 Operational Support/On-call",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": "Highest",
    "LoB": "PEG",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Q3 2026 Custody Operational Support (Misc. requests)",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": "Highest",
    "LoB": "Custody",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Q3 2026 - Core infrastructure components maintenance",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": "Medium",
    "LoB": "PEG",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Compute right-sizing rollout (Karpenter + Traefik)",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": "Medium",
    "LoB": "PEG",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Metrics outage incident action items",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": "Medium",
    "LoB": "PEG",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Migrate subnets.avax.network to l1.avax.network across all systems",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": null,
    "OKR": null,
    "Status": "Backlog",
    "Priority ": "Medium",
    "LoB": "AvaCloud",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Settl Phase 1 - Development chain bring-up on existing infrastructure",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": null,
    "OKR": null,
    "Status": "Backlog",
    "Priority ": "Medium",
    "LoB": "SETTL",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Settl Phase 2 - Dedicated AWS development account and workload migration",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": null,
    "OKR": null,
    "Status": "Backlog",
    "Priority ": "Medium",
    "LoB": "SETTL",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Upgrade Grafana agent deployment to 4.5.0 helm version",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "Selected for Development",
    "Priority ": "Medium",
    "LoB": "PEG",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": null,
    "Roadmap item": "Custody Licensed Software PoC",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "In Progress",
    "Priority ": "Medium",
    "LoB": "Custody",
    "Estimated Effort (FTE Weeks)": null,
    "Classification": null,
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": null,
    "Q3 2026 plan": "XX"
  },
  {
    "MotherEPIC": "Custody - new functionality",
    "Roadmap item": "New Signing Service (Q3 2026)",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "New",
    "Priority ": 2.0,
    "LoB": "Custody",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": 0.0,
    "Q3 2026 plan": "X"
  },
  {
    "MotherEPIC": "Custody - new functionality",
    "Roadmap item": "Infra Segregation (Q4 2026)",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "New",
    "Priority ": 3.0,
    "LoB": "Custody",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "Solution Architecture",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": 0.0,
    "Q3 2026 plan": "X"
  },
  {
    "MotherEPIC": "Custody - new functionality",
    "Roadmap item": "Platform Licensing Procedures",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "New",
    "Priority ": 1.0,
    "LoB": "Custody",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": "XL",
    "Q3 2026 plan": "XL"
  },
  {
    "MotherEPIC": "Custody - new functionality",
    "Roadmap item": "Sandbox Environment ",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "New",
    "Priority ": 0.0,
    "LoB": "Custody",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": "X",
    "Q3 2026 plan": "X"
  },
  {
    "MotherEPIC": "Maintenance",
    "Roadmap item": "Observability/incident Response",
    "Business Value/Purpose": null,
    "2026 AVL Strategy Aligned": "No",
    "OKR": null,
    "Status": "New",
    "Priority ": 0.0,
    "LoB": "Custody",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Request",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": "X",
    "Q3 2026 plan": "X"
  },
  {
    "MotherEPIC": "Technical improvementt - cost reduction",
    "Roadmap item": "Develop a process to verify archival node backup consistency",
    "Business Value/Purpose": "Develop a process to verify archival node backup consistency - result of dedicated node roll out failure/issues - skunkworks",
    "2026 AVL Strategy Aligned": "Yes",
    "OKR": null,
    "Status": "New",
    "Priority ": 2.0,
    "LoB": "PEG",
    "Estimated Effort (FTE Weeks)": 0.0,
    "Classification": "Maintenance",
    "Main Team": "SRE",
    "Dependency": null,
    "Q1 2026 plan": null,
    "Q2 2026 plan": "X",
    "Q3 2026 plan": "X"
  }
];
